### ISSUE TITLE
HTML not displaying the draw chart board and the css options menu

### ISSUE THREAD

**Issue by RoyaghRamo** [jerosoler/drawflow-theme-generator#2]
I tried launching **index.html** after installing necessary packages, but it doesn't seem to display the second _div_ which contains the drawflow demo and the css panel in which the options can be changed.

**Comment by jerosoler** [comment]
Hi @RoyaghRamo 

I have modified the packages from unpkg and it seems to work now. You can see it here: https://jerosoler.github.io/drawflow-theme-generator/

**Comment by RoyaghRamo** [comment]
> Hi @RoyaghRamo
> 
> I have modified the packages from unpkg and it seems to work now. You can see it here: https://jerosoler.github.io/drawflow-theme-generator/

Yeah, it does. Thanks.
It's a great project.
